/* @flow */

export const MONTHS_IN_YEAR = 12;

export const STUDENT_LOAN_FREE_AMOUNT = 17495;
export const STUDENT_LOAN_CONTRIBUTION = 0.09;
export const STUDENT_LOAN_YEARLY_INTEREST_RATE = 0.0125;
export const STUDENT_LOAN_MONTHLY_INTEREST_RATE = STUDENT_LOAN_YEARLY_INTEREST_RATE / MONTHS_IN_YEAR;

export const STUDENT_LOAN_REPAYMENT_URL = 'http://studentloanrepayment.co.uk';
